### PR TITLE
added mean effective stress and fixed huddleston

### LINKED ISSUE #48: Add MeanEffectiveStress and fix HudllestonEffectiveStress
Add the `MeanEffectiveStress` defined as tr(sigma)/3 and fix `HudllestonEffectiveStress` to work when `ss=0`

### PR DESCRIPTION
**Pull request by arovinelli**
This PR adds the `MeanEffectiveStress` and fix a bug in `HudllestonEffectiveStress` preventing some calculation to run. 
close #48

### CODE REVIEW

File: src/damage.cxx [hunk 1]
```diff
@@ -630,10 +664,17 @@ int HuddlestonEffectiveStress::effective(const double * const s, double & eff) c
...
   double ss = sqrt(-3.0 * I2pv + I2v);
 
+  // check if ss = 0.0
+  if ( ss == 0.)
+  {
+    eff = 0.;
+    return 0;
+  }
+
+
```
Comment (chakra34) [inline src/damage.cxx]: should there be any check for ss !=  1.0 ?

File: doc/sphinx/damage/effective/meanstress.rst [hunk 2]
```diff
@@ -0,0 +1,24 @@
+Mean effective stress
+==========================
+
+Overview
+--------
+
+This is the standard von Mises effective stress defined by
```
Comment (reverendbedford) [inline doc/sphinx/damage/effective/meanstress.rst]: No it is not.

File: src/damage.cxx [hunk 3]
```diff
@@ -594,6 +594,40 @@ int VonMisesEffectiveStress::deffective(const double * const s, double * const d
...
+  eff = (s[0] + s[1] + s[2]) / 3.0;
+
+  return 0;
+}
+
+int MeanEffectiveStress::deffective(const double *const s,
+                                    double *const deff) const {
+
+  for (int i = 0; i < 6; i++)
+    if (i < 3)
```
Comment (reverendbedford) [inline src/damage.cxx]: Use brackets...
